language: node_js
node_js:
 - "0.12"
services:
 - mongodb
install:
 - npm install phantomjs -g
 - npm install mocha-phantomjs -g
 - npm install gulp -g
 - npm install
before_script:
 - phantomjs -v
 - mocha-phantomjs -version
script:
 - npm run testClient