language: node_js
node_js:
 - "0.12"
services:
 - mongodb
env:
 - node_env=travis
install:
 - npm install phantomjs -g
 - npm install mocha-phantomjs -g
 - npm install gulp -g
 - npm install
before_script:
 - sudo service mongod start
 - sleep 15
 - phantomjs -v
script:
 - npm run testClient
 - npm run testServer